source "https://rubygems.org"

#ruby=ruby-1.9.3
#ruby-gemset=bikestation

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sequel'
gem 'sqlite3', group: :development
gem 'pg', group: :production
gem 'rack-parser'

