default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: SmartBike_development
  username: smartbike
  password: smartbike_pwd
  host: localhost
  port: 5432

test:
  <<: *default
  database: SmartBike_test
  username: smartbike
  password: smartbike_pwd
  host: localhost
  port: 5432

production:
  <<: *default
  database: SmartBike_production
  username: SmartBike
  password: <%= ENV['SMARTBIKE_DATABASE_PASSWORD'] %>
