# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01e2963f36b2693570883eada5665aa6324bdfc7435c119786b8d3232835f9b6c234c83bc1ab9cb8b27489ff325df3e7d2ea911745556f30b603373fdeebbede
  api_key: AIzaSyDIUSZ4tdOYfFjRHXP5aaB1T2S8t0NAQE0

test:
  secret_key_base: c02ea9dd1d70d87857c92bd6dc6bdd8ae917e34d36671328d59f045a9ef4c49c8b9a56ea5e136c17c487a8e4e0e976d8517432bf89f7bba38a0f19fc5045f384

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_key: <%= ENV["API_KEY"] %>
